env:
  global:
    - BINTRAY_USER=rootlogin
    - secure: "i2TooRNggdvBl3WfeKq62nVHvsoHrbF0jZYXHebRKBW67JItCFc28efTuTYA14gnOk1fcN+gurp5MsB4zYePakmWbU7Eha5PaKBgjoGDc50LlAsmouVfRoU4Ld8VffB5FVo+Gv+du7w+hfJ8MAo4t2Qyomcf8+Plb22HnULYhnvymJ1c+uCYpbkgwBupaEkdGpINbZRVJuAi45Db9bcAUHQWDN5HFbVsdgVtSsePK9pHu7HaQQLQSHrjKLRm6jfn0PV+oBA4bMmf3vbQ+i9cWYGPBuJY0BRF23DBpxDgeSUt3Be7PqcJ1FtAltS6QJNKAk572J0ZDF7k+YF1ieJ+viwSgJjb9SCkPvte8Dylg1Jlufo/h81CzOs1JGd+LUov9QIEuJYKLuHP7TV1gVXWCuCaT5PekVblafm289gNsRaXurLRF67k8vKOlDJMYHy2IrEMPIj5wmqOG0lHPQeWN/rXFgGMYjGdAhlZrhskNc2v7SiIPtkp8e8Qh1rAgvzkGbU4BEWRvIkGYIN9DqGvxwSs5Ly+JkpDe9r4QXGDO03asa5CyDCxc7ZA3kGiwIHa3Q5QHBpaCv5JXvIn7ofJeHPyPvnr6dx3mHOGsy0lU9M4noiEB2AQe9Pd7Zqu1N04Qr4VtX0D6r9FYYNV8a6vMmi7Nk3T1FPzhqfy0edUqvI="

jobs:
  include:
    - language: java
      jdk: openjdk11

      git:
        depth: false

      cache:
        directories:
          - '$HOME/.m2/repository'
          - '$HOME/.sonar/cache'

      script:
        - mvn clean package

deploy:
  - provider: script
    script: |
      export REZEPTVERWALTUNG_VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
      curl -T "target/rezeptverwaltung-$REZEPTVERWALTUNG_VERSION.jar" -u "$BINTRAY_USER:$BINTRAY_API_KEY" -H "X-Bintray-Publish:1" -H "X-Bintray-Package:linux" -H "X-Bintray-Version:latest-$(date +%Y-%m-%d)" -H "X-Bintray-Override:1" "https://api.bintray.com/content/rootlogin/rezeptverwaltung/latest-$(date +%Y-%m-%d)/rezeptverwaltung.jar"
      curl -T "target/rezeptverwaltung-$REZEPTVERWALTUNG_VERSION.exe" -u "$BINTRAY_USER:$BINTRAY_API_KEY" -H "X-Bintray-Publish:1" -H "X-Bintray-Package:windows" -H "X-Bintray-Version:latest-$(date +%Y-%m-%d)" -H "X-Bintray-Override:1" "https://api.bintray.com/content/rootlogin/rezeptverwaltung/latest-$(date +%Y-%m-%d)/rezeptverwaltung.exe"
    skip_cleanup: true
    on:
      branch: master

#  provider: bintray
#  user: "rootlogin"
#  key:
#    secure: "gC6qdtBOqz1GikkloBhe/p9aCzdA0ozx22UMR7HaglqgWn2nkAQO5XdAWOptOFa775+B2IgRUMJFMF0yonEcQtx5cCrII5rzuejDLfaYiVEz6MbYYhD4Z0QJ3Bj7iUABUGBrVWTnsTSnC8zB3J1taorVCS2juaVTrM8q5lF9Z0eOegnc40q0uU9NY6PfwoGNwuukG11mhoDvHS4xrWxthRO+xoYoHcR5BYrZ/u2JakcmFrInTf/hz50WnltPBTIXMytqItjU+KDXrv7/HP3R+rSxf9zGC1/nIKOGaWGhNE8n0K/vL9TEoNEWP7unuh+v86XZlcV/sqdL7f84+mx7ChuuFIw1MkHUC00FtAkaAcjL6wtPnyvNySi4215KH7vC3KF2iIX4JG1YHhnEDgn9e8pN/9UHvQY62qhpUd5mqQ2QP8NBBeUQflFWpNXhbLi++HqFrRiON+PB6OQ/sig5SoRytcbMhYeoVs+v4Yo4l7R1mRn0cS6PlDE3W15vwrI3A3ryaX6qx6Ecl7uURRA2Ss3G/XqN5Vv9umqB50lp9nCXIjq9JPoJi8ofQTdekCmIwmjCtd1CS/fJ6zA9GZVQucpTgzsXJdcg1RwhdVHOgUSVdmpwguvaFZm+A64jxRtx+axB4dUU5TnhyuFgZk7apVOQmV0HjPcP05I/tBmVE3I="
#  on:
#    all_branches: true

notifications:
  email:
  - hello@rootlogin.ch
